---
title: Kettapp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
