---
title: KettApp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Development team of mobile apps
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
